spring:
  application:
    name: core-spring
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=True
    username: root
    password: root1234
  flyway:
    clean-disabled: true
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate